name: get_it_tutorial
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # TODO 1: include GetIt as a dependency
  get_it: ^7.2.0

  # This package contains a set of high-level functions and classes that make it easy to consume HTTP resources.
  http: any

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/doc_images/
  #   - images/a_dot_ham.jpeg